add same parameters as in tests
Assuming that a novice will look at the test file to determine what their code is supposed to do, the stub might as well include the same parameters.

Exception: new, generic parameter name in word-count.R